#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Protect master from accidental commits.
echo -e "===\n>> Pre-commit Hook:: Checking branch name..."
branchName=$(git branch | grep '*' | sed 's/* //')

if [ $branchName == 'master' ]
then
  echo -e "\n🚫 Commit directly to master branch is not allowed!\n" && exit 1
fi

if [ $branchName == 'main' ]
then
   echo -e "\n🚫 Commit directly to main branch is not allowed!\n" && exit 1
fi

if [ $branchName == 'develop' ]
then
   echo -e "\n🚫 Commit directly to develop branch is not allowed! Please create your own branch with develop/branch. \n" && exit 1
fi

echo -e ">> Finish checking branch name \n==="

npm run lint
npm run test