#!/usr/bin/env sh
# Prevents force-pushing to master
. "$(dirname -- "$0")/_/husky.sh"

echo -e "===\n>> Pre-push Hook: Checking branch name..."

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|main)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, Please create your own branch with develop/branch." && exit 1
fi

echo -e ">> Finish checking branch name \n==="

exit 0