name: Deploy QA Netlify

on:
  pull_request:
  push:
    branches:
      - develop/*

#Prevent the error with the enviroment in Netlify
env:
  CI: false

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node version: "16"

      - name: Install Dependecies
        run: npm install

      - name: Test Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test

  deploy:
    needs: validation
    environment:
      name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install

      - name: Set Homepage
        run: npm run Sethomepage

      - name: Build
        run: CI=false npm run build

      - name: deploy to Netlify
        run: netlify deploy -p --auth ${{secrets.AUTH_TOKEN_QA}} --site ${{secrets.SITE_ID_QA}}

      - name: Run test
        run: npm run test

  PR:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8

        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Build
        run: echo "building project"

      - name: Create PR
        uses: medlypharmacy/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HEAD_BRANCH: develop/config
          BASE_BRANCH: main
