name: Deploy QA Netlify

on:
  pull_request:
  push:
    branches:
      - develop/*

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node version: "16"

      - name: Install Dependecies
        run: npm install

      - name: Test Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test

  deploy:
    needs: validation
    environment:
      name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install

      - name: Set Homepage
        run: npm run Sethomepage

      - name: Build
        run: CI=false npm run build

      - name: deploy to Netlify
        run: netlify deploy -p --auth ${{secrets.AUTH_TOKEN_QA}} --site ${{secrets.SITE_ID_QA}}

      - name: Run test
        run: npm run test
